
pipeline {
    agent any
    environment {
       registry = "go-microservice/auth"
       GOCACHE = "/tmp"
   }
    stages {
       stage('Build') {
           agent {
               docker {
                   image 'golang:alpine'
               }
           }
           steps {
               // Create our project directory.
               command 'pwd'
               command 'cd ${GOPATH}/src'
               command 'mkdir -p ${GOPATH}/src/hello-world'
               // Copy all files in our Jenkins workspace to our project directory.
               command 'cp -r ${WORKSPACE}/* ${GOPATH}/src/hello-world'
               // Build the app.
               command 'go build'
           }
       }
       stage('Test') {
           agent {
               docker {
                   image 'golang'
               }
           }
           steps {
               // Create our project directory.
               command 'cd ${GOPATH}/src'
               command 'mkdir -p ${GOPATH}/src/hello-world'
               // Copy all files in our Jenkins workspace to our project directory.
               command 'cp -r ${WORKSPACE}/* ${GOPATH}/src/hello-world'
               // Remove cached test results.
               command 'go clean -cache'
               // Run Unit Tests.
               command 'go test ./... -v -short'
           }
       }
       stage('Publish') {
           environment {
               registryCredential = 'privateregistry'
           }
           steps{
               script {
                   def appimage = docker.build registry + ":$BUILD_NUMBER"
                   docker.withRegistry( 'http://registry:5000', registryCredential ) {
                       appimage.push()
                       appimage.push('latest')
                   }
               }
           }
       }
       stage ('Deploy') {
           steps {
               script{
                   def image_id = registry + ":$BUILD_NUMBER"
                   command "ansible-playbook  playbook.yaml --extra-vars \"image_id=${image_id}\""
               }
           }
       }
   }
}