- hosts: localhost
  become: yes
  vars:
    jenkins_hostname: jenkins
    docker_users:
    - jenkins
  tasks:
  - name: Deploy the service
    k8s:
      state: present
      definition: ""
      validate_certs: no
      namespace: default
  - name: Deploy the application
    k8s:
      state: present
      validate_certs: no
      namespace: default
      definition: ""